### ISSUE TITLE
Repo install does not like it when repository has a dash in its name

### ISSUE THREAD

**Issue by Oswinska** [pumpkin-py/pumpkin.py#72]
Keeping in mind that all official modules do not use a dash in their names.
When i created a repo that does include a dash in its name. Trying to install lead to an error saying
`'Repository' object has no attribute 'kwargs'`
After applying a "fix" to `pumpkin.py/modules/base/admin/module.py`

```diff
class Repository:
    """Module repository.

    This object is used when working with the **repo** command.
    """

    def __init__(
        self,
        path: str,
        valid: bool,
        message: str,
        message_vars: dict = None,
        *,
        name: str = None,
        modules: tuple = None,
        version: str = None,
    ):
+       self.kwargs = {}
        self.directory: str = os.path.basename(path)
        self.valid: bool = valid
```
        
New "error" showed up saying: `Repository has an invalid name:((name))`  That lead me to `__init__.py` in the root of my module. Where i changed `__name__ = "pumpkin-extensions"` to  `__name__ = "template"` as is shown in [Pumpkin.py Template](https://github.com/pumpkin-py/pumpkin-template/blob/main/__init__.py) 

Trying to repo install that returned a success. In my frustration i rewrote `__init__.py` again, and this time instead of using my repo name i removed the dash and used `"pumpkinextensions"`. Letting the bot install that returned as a succsess.

While it is entirely possible that my stupidity and incompetency created this problem. It is stated in [Creating a repository](https://pumpkinpy.readthedocs.io/en/latest/development/repository.html) that dashes are supported.

Please take a look at it :prayge:

**Comment by CrafterSvK** [comment]
https://github.com/pumpkin-py/pumpkin.py/blob/f31beb06347fa44c46c7d8c9ac3d5bca11e34cb1/modules/base/admin/module.py#L549 Documentation states that it can be `[a-z-]+` but code uses `[a-z_]+` regex.

**Comment by sinus-x** [comment]
The documentation is wrong. Imported repository acts as Python module, so dashes cannot be allowed.
