### ISSUE TITLE
Version decorators

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin.py#80]
Add command decorator to limit discord.py version.

It will act as an additional check: if will do nothing if the local version is equal or higher, but abort if it's lower. Abort = reply that the command is not available and return False.

**Comment by CrafterSvK** [comment]
I will try to implement this feature.

**Comment by sinus-x** [comment]
- Since the `ctx` is implements `Messageable` you can directly use `ctx.reply()` and send the message. Catch all `discord.HTTPException`s, don't do anything on error. (Actually, `with contextlib.suppress(discord.HTTPException)` will do the trick.)
- Major and minor _should_ be enough, but I guess we can also do patch as well. Both minor and patch should be optional. Ignore `RC` and other pre-release versioning and pretend it does not exist.
